name: example

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - uses: mcbenjemaa/gh-request-token@v1
        id: request_token
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Get the output
        run: echo "Github self-hosted runner registration-token ${{ steps.request_token.outputs.registration-token }}"
